[package]
name = "rocket-test"
version = "0.1.0"
authors = ["kpensec <kevin.pensec@gmail.com>"]

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
juniper = "0.11"
juniper_rocket = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
